### ISSUE TITLE
Anyway to increase font-size in HTML PREVIEW?

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-better-dictionaries#19]
I changed all the font-size values to 300% in dict-entry.css

Though I still don't see any discernible difference, in fact NOTHING CHANGED AT ALL 😞 😢.

I know this project has been left alone since a century ago but putting this issue out there in case anyone in the future comes across it 🙃

✌️

**Comment by yarub123** [comment]
@mr-pennyworth You the best. Appreciate the follow up man. Thank you.

**Comment by mr-pennyworth** [comment]
@yarub123 yup, only the above entry. All the other entries just scale it up or down (they are of the form `font-size: x%`).
Keep in mind though, that the `dict-entry.css` to edit isn't the one in the workflow folder, but the one in the data folder.

1. Type `.dict-data` in Alfred and hit enter.
2. Navigate to `<dictionary-name>/html/dict-entry.css` and edit it.

For example, on my system, it is `/Users/<UserName>/Library/Application Support/Alfred/Workflow Data/mr.pennyworth.betterDicts/com-apple-dictionary-NOAD/html/dict-entry.css`

**Comment by mr-pennyworth** [comment]
@yarub123 that looks like an old version of `AlfredExtraPane`?
You can check it in the workflow folder
<img width="725" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/74945464/e7515f94-8103-46cf-8fcd-7158acb4563e">

Another possibility is that maybe `AlfredExtraPane` is installed somewhere else too and that is being invoked instead of the one in the workflow folder?

**Comment by yarub123** [comment]
I saw your reply earlier, but only just now got to messing around with it. Unfortunately same error.

- I completely removed any betterdict workflows (after also resetting it). Removed alfredextrapane from privacy>accessibility. (∴ no AlfredExtraPanes left, also double checked workflow directories, cleaned out!)
- Tried another fresh install of 0.2.4
- Got the error
- Removed it again, emptied trash, restarted computer
- Tried again, same error 🙃.

It's nbd I can always just use the 0.1.6 again. I made sure to compress backups of old workflows.

**Comment by mr-pennyworth** [comment]
Hmm sorry @yarub123 that didn't help :(
curious about the version of `AlfredExtraPane` you're using. You can see the version in finder: 
<img width="725" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/74945464/69fb34e9-d50a-46a6-b9f4-e1b3fc272c10">

Once you confirm you're using version `0.1.1`, would be good to also confirm that the one that's running is the same as the one in the workflow dir `ps aux | grep AlfredExtraPane` the path printed here should be the same as what you saw in finder.

**Comment by mr-pennyworth** [comment]
The issue is likely due to https://github.com/mr-pennyworth/AlfredSwift/issues/1

**Comment by yarub123** [comment]
Yup 0.1.1 in the directory. And yes ps aux matches same directory. No discrepancy.

Thanks for following up and bringing to attention that other post, that is very interesting. Now I'm even more curious as to the cause, considering someone else had it haha. No worries though. I wonder what this Pane version is doing different from the previous one that is causing it to output this error...

**Comment by mr-pennyworth** [comment]
This should fix the issue: https://github.com/mr-pennyworth/AlfredSwift/commit/f258d4871e65b88201a72860e73049c3aa1e82cd

And once the latest build https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.5 should reflect that change :)

**Comment by yarub123** [comment]
@mr-pennyworth Yup that fixed it.... BUT now there's another issue 🙃

I'm sorry man, alright. Sorry for being the bearer of bad news 😩. I'm going to put the debug in here. First part is same as yesterdays, that part isn't a big deal. 2nd part is what's causing the issue:

(1) running .setup-better-dict 👇
```
[14:56:29.281] Better Dictionaries[Keyword] Processing complete
[14:56:29.283] Better Dictionaries[Keyword] Passing output '' to Run Script
[14:56:29.285] ERROR: Better Dictionaries[Run Script] xattr: ./AlfredExtraPane.app: No such xattr: com.apple.quarantine
xattr: ./alfred-dict-server: No such xattr: com.apple.quarantine
xattr: ./BetterDict: No such xattr: com.apple.quarantine
xattr: ./cocoaDialog.app: No such xattr: com.apple.quarantine
xattr: ./jq: No such xattr: com.apple.quarantine
No matching processes belonging to you were found
```

(2) running .dict-import 👇
```
[14:56:53.861] Better Dictionaries[Script Filter] Queuing argument '(null)'
[14:56:56.219] Better Dictionaries[Script Filter] Script with argv '(null)' finished
[14:56:56.225] ERROR: Better Dictionaries[Script Filter] Code 1: Traceback (most recent call last):
  File "BetterDict.py", line 418, in <module>
  File "BetterDict.py", line 394, in list_unimported_dicts
  File "BetterDict.py", line 244, in get_dict_name
KeyError: 'CFBundleDisplayName'
[16317] Failed to execute script 'BetterDict' due to unhandled exception!
```

**Comment by mr-pennyworth** [comment]
@yarub123 the import error should (hopefully 🤞🏼) be fixed in https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.6

I'm still curious about your dictionary setup that caused the issue though.
So, do share the output if that's okay with you 😇

**Comment by yarub123** [comment]
Awesome. That helped. It didn't work at first because there was no db.log. So I used db.log from one of the archived backups, put that into the directory, and the importing process worked.

And yes of course I can give you that output, you've been already more than helpful and patient and I sincerely appreciate you for that. It's the least I can do. Thing is, it's a PRETTY LONG file, so I uploaded it [here](https://github.com/yarub123/Alf/blob/main/dictionariesList.json)

**Comment by mr-pennyworth** [comment]
Thanks @yarub123! looking at the JSON, I see that there's only one dictionary which does not have `CFBundleDisplayName`: "TTY Abbreviations"

my laptop does not have that dictionary :(
looks like 1a2a057 fixed it 🎉

**Comment by yarub123** [comment]
@mr-pennyworth Honestly, have no clue what that dictionary could possibly be. But yes, all good now! Great stuff man. Thanks again ❤️

**Comment by olivergiangvu** [comment]
> Thanks @yarub123 for the bug report! Changing the `dict-entry.css` wasn't taking effect because `font-size` was before `font`. This fixes it: <img alt="image" width="483" src="https://private-user-images.githubusercontent.com/74945464/305722588-e9cf5de8-2dbc-4050-8f0b-1b3fff1c3c13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjU0ODgsIm5iZiI6MTcyMjQyNTE4OCwicGF0aCI6Ii83NDk0NTQ2NC8zMDU3MjI1ODgtZTljZjVkZTgtMmRiYy00MDUwLThmMGItMWIzZmZmMWMzYzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NjI4ZTY5YjQ0OGYwZGNmODYxNTE4ZWU2NGMzNDA1MzJiZjRiNzYzZjk0ZWY3Y2QyMzkyNWRhZWNhYmJiNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZZ0cwI0YASkmgxPmDCY4cooxDb3LCLM8M_icrYC_CoA">
> 
> I have made the same change and it is part of the latest build 😇

I follow this but the font size still not chnage for me I am on the latest build for both Better Dictionary and Extra Pane

**Comment by yarub123** [comment]
@olivergiangvu at the bottom do you see the "font-size: calc(var(--result...."?

Simply change that to whatever font you want... don't make it a calc variable... so change it to for ex, "font-size: 14"... if you want you can copy and paste this over in dict-entry.css. Let me know if it works:

```
{
    font: -apple-system-body;
    font-family: -apple-system;
    margin-left: 0.9em;
    margin-right: 0.9em;
    margin-top: 1.0em;
    margin-bottom: 1.5em;
    font-size: 14pt;
}
```

**Comment by olivergiangvu** [comment]
> @olivergiangvu at the bottom do you see the "font-size: calc(var(--result...."?
> 
> Simply change that to whatever font you want... don't make it a calc variable... so change it to for ex, "font-size: 14"... if you want you can copy and paste this over in dict-entry.css. Let me know if it works:
> 
> ```
> {
>     font: -apple-system-body;
>     font-family: -apple-system;
>     margin-left: 0.9em;
>     margin-right: 0.9em;
>     margin-top: 1.0em;
>     margin-bottom: 1.5em;
>     font-size: 14pt;
> }
> ```

![CleanShot 2024-08-04 at 19 34 51](https://github.com/user-attachments/assets/bed1487f-39fe-40f2-a96f-d1fe3dc71175)
![CleanShot 2024-08-04 at 19 35 07](https://github.com/user-attachments/assets/0a7ed8b3-3502-4889-b300-3b81cd2666d2)
font size still not change for me 🥲

**Comment by mr-pennyworth** [comment]
Thanks @olivergiangvu for the report and @yarub123 for helping out!

The issue is that somehow, in @olivergiangvu's setup, the `dict-entry.css` in the workflow folder isn't correctly synced (via a hard link) to the `dict-entry.css` inside the dictionary data folder.

I have added support for specifying custom style to AlfredExtraPane:
https://github.com/mr-pennyworth/alfred-extra-pane/commit/0690380144d0f07dd83bc060f659d9c1501a0b27

With that, now there is no more need to have multiple `dict-entry.css` and link them via a hard link.
I'll publish the fix for better dictionaries shortly.

**Comment by mr-pennyworth** [comment]
Fixed with https://github.com/mr-pennyworth/alfred-better-dictionaries/commit/8a28f81e2070e869f0d2279c94e96473accfe068

Latest release should have the fix: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.17

**Comment by olivergiangvu** [comment]
I try the new ver but now the font look kind of weird
![CleanShot 2024-08-04 at 22 52 25](https://github.com/user-attachments/assets/bc059b26-cf5c-4733-ab0e-3c9f43724592)

**Comment by mr-pennyworth** [comment]
Whoops! I forgot to include the extra pane conf! 🙈 
Adding this file as `extra-pane-config.json` to your workflow directory should fix it :)
```json
[{
  "alignment" : {
    "horizontal" : {"placement" : "right", "width" : 300, "minHeight" : 400}},
  "customCSSFilename": "dict-entry.css"
}]
```

**Comment by olivergiangvu** [comment]
> Whoops! I forgot to include the extra pane conf! 🙈 Adding this file as `extra-pane-config.json` to your workflow directory should fix it :)
> 
> ```json
> [{
>   "alignment" : {
>     "horizontal" : {"placement" : "right", "width" : 300, "minHeight" : 400}},
>   "customCSSFilename": "dict-entry.css"
> }]
> ```
> 
> I have also updated the release to include this file

It worked now! Thank you a lot!

**Comment by yarub123** [comment]
@mr-pennyworth Beautiful work as always, brothaman. Thanks for the extra info & detail.
